const boyImg = ['🥵','🥴','🤠','🤓','👦','🧔‍♂️','👨‍🦳'];
const girlImg = ['🥳','😴','🥺','👧','🙅‍♀️','🙍‍♀️','👱‍♀️','👩‍🦰'];

const persons = [
    { gender: "boy", personName: "Jerry"},
    { gender: "girl", personName: "Jessica"},
    { gender: "girl", personName: "Lauren"},
    { gender: "boy", personName: "Lionel"},
    { gender: "girl", personName: "Joan"},
    { gender: "girl", personName: "Anna"},
    { gender: "boy", personName: "Fabian"},
    { gender: "boy", personName: "Thomas"},
    { gender: "boy", personName: "Theodor"},
    { gender: "girl", personName: "Diana"},
    { gender: "girl", personName: "Atara"},
    { gender: "girl", personName: "Avishag"},
    { gender: "girl", personName: "Mariel"},
    { gender: "girl", personName: "Maayan"},
    { gender: "girl", personName: "Tamar"},
    { gender: "boy", personName: "Daniel"},
    { gender: "boy", personName: "Ariel"},
    { gender: "girl", personName: "Elisheva"},
    { gender: "girl", personName: "Eliana"},
    { gender: "girl", personName: "Neomi"},
    { gender: "girl", personName: "Veronica"},
    { gender: "boy", personName: "Leonardo"},
    { gender: "boy", personName: "Nataniel"},
    { gender: "boy", personName: "Ricardo"},
    { gender: "boy", personName: "Michael"},
    { gender: "girl", personName: "Michaela"},
    { gender: "girl", personName: "Daniela"},
    { gender: "girl", personName: "Avigail"},
    { gender: "girl", personName: "Ayelet"},
    { gender: "boy", personName: "Asher"},
    { gender: "boy", personName: "Aryeh"},
    { gender: "boy", personName: "Schmuel"},
    { gender: "boy", personName: "Tal"},
    { gender: "girl", personName: "Tali"},
    { gender: "girl", personName: "Avital"},
    { gender: "girl", personName: "Efrat"},
]; 